# Generated by Django 4.1.7 on 2023-04-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex')], max_length=1)),
                ('inches_height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inches_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color_description', models.CharField(max_length=255)),
                ('gsm', models.PositiveIntegerField()),
                ('fabric_description', models.CharField(max_length=255)),
                ('order_no', models.PositiveIntegerField(default=None, null=True)),
                ('other_descriptions', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('order_details', models.TextField()),
                ('contact_person', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
