# Generated by Django 4.1.7 on 2023-04-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_order_no'),
    ]

    operations = [
    ]
