# Generated by Django 4.1.7 on 2023-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20230406_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gsm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inches_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='inches_width',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order_details',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
        migrations.AddField(
            model_name='product',
            name='color_chart',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], default='red', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L')], default='s', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='contact_person',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabric_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='men', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(choices=[('shirt', 'Shirt'), ('pants', 'Pants'), ('shoes', 'Shoes')], default='shirt', max_length=50),
        ),
    ]
