# Generated by Django 4.1.7 on 2023-04-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_color_description_remove_product_gsm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='region_chart',
            field=models.CharField(choices=[('A', 'Asia'), ('US', 'USA'), ('EU', 'Europe')], default='red', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_chart',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], default='Asia', max_length=10),
        ),
    ]
