# Generated by Django 4.1.7 on 2023-04-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_region_chart_alter_product_color_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_chart',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue')], default='red', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='region_chart',
            field=models.CharField(choices=[('A', 'Asia'), ('US', 'USA'), ('EU', 'Europe')], default='Asia', max_length=10),
        ),
    ]
