# Generated by Django 4.1.7 on 2023-04-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNFInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnf_information', models.CharField(max_length=255, verbose_name='CNF Information')),
                ('cnf_no', models.CharField(max_length=50, verbose_name='CNF No')),
                ('order_no', models.CharField(default=True, max_length=50, null=True, verbose_name='Order no')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Contact Person')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('street', models.CharField(max_length=255, verbose_name='Street')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('best_time_to_call', models.CharField(max_length=255, verbose_name='Best Time to Call')),
            ],
        ),
    ]
