# Generated by Django 4.1.7 on 2023-04-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnfinfo',
            name='order_no',
        ),
    ]
