# Generated by Django 4.1.7 on 2023-04-14 01:27

import datetime
from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20)),
                ('order_no', models.CharField(max_length=20)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('order_delivery_status', models.CharField(max_length=20, null=True)),
                ('delivered_on', models.DateField(null=True, validators=[orders.models.Date_validation])),
                ('cnf_no', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
